{
  logger.error("Exception in Foo verticle!",t);
}
