{
  try {
    Assert.assertNotNull(object);
  }
 catch (  AssertionError e) {
    handleThrowable(e);
  }
}
