{
  checkThread();
  try {
    Assert.assertFalse(message,condition);
  }
 catch (  AssertionError e) {
    handleThrowable(e);
  }
}
